language: cpp

# cross toolchain (used as a base for multiarch cross-compilation configurations below)
include: &toolchain_linux_cross
  dist: trusty
  sudo: required # for dpkg --add-architecture locking

# armhf toolchain
include: &toolchain_linux_armhf
  <<: *toolchain_linux_cross
  env:
    - LABEL=armhf_linux
    - CROSS_TOOLCHAIN=true
    - ARCH=armhf
    - NPM_ARCH=arm
    - GNU_TRIPLET=arm-linux-gnueabihf
    - GNU_MULTILIB_TRIPLET=arm-linux-gnueabihf
    - GPP_COMPILER=arm-linux-gnueabihf-g++
    - GCC_COMPILER=arm-linux-gnueabihf-gcc

matrix:
  include:
  - os: linux
    <<: *toolchain_linux_armhf

before_install:
  - apt-get install -y snapcraft

script:
  - snapcraft

notifications:
  email: false
